-- VHDL Entity The_Reverb_Revolutionary_lib.Audio_Echo_sample_compression.generatedInstance
--
-- Created:
--          by - matho019.student-liu.se (muxen2-109.ad.liu.se)
--          at - 16:01:31 10/07/24
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY Audio_Echo_sample_compression IS
   PORT( 
      fpga_clk     : IN     std_logic;
      fpga_reset_n : IN     std_logic
   );

END Audio_Echo_sample_compression ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF Audio_Echo_sample_compression IS 
BEGIN


END generatedInstance;
