-- VHDL Entity The_Reverb_Revolutionary_lib.Audio_Balance.generatedInstance
--
-- Created:
--          by - akhpr339.student-liu.se (muxen2-108.ad.liu.se)
--          at - 18:30:44 10/08/24
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
USE ieee.std_logic_arith.all;
USE ieee.std_logic_unsigned.all;

ENTITY Audio_Balance IS
   PORT( 
      Audio_L_output  : OUT    std_logic_vector (15 DOWNTO 0);
      Audio_R_output  : OUT    std_logic_vector (15 DOWNTO 0);
      Audio_sample_3  : IN     std_logic_vector (15 DOWNTO 0);
      Balance_setting : IN     std_logic_vector (3 DOWNTO 0);
      fpga_clk        : IN     std_logic;
      fpga_reset_n    : IN     std_logic
   );

END Audio_Balance ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF Audio_Balance IS 
BEGIN


END generatedInstance;
