-- VHDL Entity The_Reverb_Revolutionary_lib.Audio_codec_block.symbol
--
-- Created:
--          by - matho019.student-liu.se (muxen2-112.ad.liu.se)
--          at - 17:12:32 10/22/24
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY Audio_codec_block IS
   PORT( 
      Audio_L_output : IN     std_logic_vector (15 DOWNTO 0);
      Audio_R_output : IN     std_logic_vector (15 DOWNTO 0);
      adcdat         : IN     std_logic;
      fpga_clk       : IN     std_logic;
      fpga_reset_n   : IN     std_logic;
      adclrck        : OUT    std_logic;
      audio_valid    : OUT    std_logic;
      bclk           : OUT    std_logic;
      config_done    : OUT    std_logic;
      dacdat         : OUT    std_logic;
      daclrck        : OUT    std_logic;
      db             : OUT    std_logic_vector (17 DOWNTO 0);
      i2c_scl        : OUT    std_logic;
      sample_l       : OUT    std_logic_vector (15 DOWNTO 0);
      sample_r       : OUT    std_logic_vector (15 DOWNTO 0);
      xck            : OUT    std_logic;
      i2c_sda        : INOUT  std_logic
   );

-- Declarations

END Audio_codec_block ;

--
-- VHDL Architecture The_Reverb_Revolutionary_lib.Audio_codec_block.struct
--
-- Created:
--          by - matho019.student-liu.se (muxen2-112.ad.liu.se)
--          at - 17:12:32 10/22/24
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY The_Reverb_Revolutionary_lib;

ARCHITECTURE struct OF Audio_codec_block IS

   -- Architecture declarations

   -- Internal signal declarations

   -- Implicit buffer signal declarations
   SIGNAL config_done_internal : std_logic;


   -- Component Declarations
   COMPONENT Audio_codec_config
   PORT (
      fpga_clk     : IN     std_logic ;
      fpga_reset_n : IN     std_logic ;
      config_done  : OUT    std_logic ;
      i2c_sda      : INOUT  std_logic ;
      i2c_scl      : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT Audio_i2s_interface
   PORT (
      fpga_clk       : IN     std_logic ;
      fpga_reset_n   : IN     std_logic ;
      config_done    : IN     std_logic ;
      Audio_L_output : IN     std_logic_vector (15 DOWNTO 0);
      Audio_R_output : IN     std_logic_vector (15 DOWNTO 0);
      adcdat         : IN     std_logic ;
      sample_l       : OUT    std_logic_vector (15 DOWNTO 0);
      sample_r       : OUT    std_logic_vector (15 DOWNTO 0);
      audio_valid    : OUT    std_logic ;
      dacdat         : OUT    std_logic ;
      xck            : OUT    std_logic ;
      db             : OUT    std_logic_vector (17 DOWNTO 0);
      adclrck        : OUT    std_logic ;
      daclrck        : OUT    std_logic ;
      bclk           : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Audio_codec_config USE ENTITY The_Reverb_Revolutionary_lib.Audio_codec_config;
   FOR ALL : Audio_i2s_interface USE ENTITY The_Reverb_Revolutionary_lib.Audio_i2s_interface;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : Audio_codec_config
      PORT MAP (
         fpga_clk     => fpga_clk,
         fpga_reset_n => fpga_reset_n,
         config_done  => config_done_internal,
         i2c_sda      => i2c_sda,
         i2c_scl      => i2c_scl
      );
   U_2 : Audio_i2s_interface
      PORT MAP (
         fpga_clk       => fpga_clk,
         fpga_reset_n   => fpga_reset_n,
         config_done    => config_done_internal,
         Audio_L_output => Audio_L_output,
         Audio_R_output => Audio_R_output,
         adcdat         => adcdat,
         sample_l       => sample_l,
         sample_r       => sample_r,
         audio_valid    => audio_valid,
         dacdat         => dacdat,
         xck            => xck,
         db             => db,
         adclrck        => adclrck,
         daclrck        => daclrck,
         bclk           => bclk
      );

   -- Implicit buffered output assignments
   config_done <= config_done_internal;

END struct;
