-- VHDL Entity The_Reverb_Revolutionary_lib.CONTROL_Subsystem.symbol
--
-- Created:
--          by - matho019.student-liu.se (muxen2-113.ad.liu.se)
--          at - 13:53:44 10/02/24
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY CONTROL_Subsystem IS
   PORT( 
      fpga_clk            : IN     std_logic;
      fpga_reset_n        : IN     std_logic;
      kb_clk              : IN     std_logic;
      kb_data             : IN     std_logic;
      Balance_setting     : OUT    std_logic_vector (3 DOWNTO 0);
      Echo_room_setting   : OUT    std_logic_vector (3 DOWNTO 0);
      Echo_volume_setting : OUT    std_logic_vector (3 DOWNTO 0);
      Hex0                : OUT    std_logic_vector (6 DOWNTO 0);
      Hex1                : OUT    std_logic_vector (6 DOWNTO 0);
      Hex2                : OUT    std_logic_vector (6 DOWNTO 0);
      Hex6                : OUT    std_logic_vector (6 DOWNTO 0);
      Hex7                : OUT    std_logic_vector (6 DOWNTO 0);
      Selected_setting    : OUT    std_logic_vector (1 DOWNTO 0);
      Volume_setting      : OUT    std_logic_vector (3 DOWNTO 0);
      db                  : OUT    std_logic_vector (9 DOWNTO 0)
   );

-- Declarations

type exemplar_string_array is array (natural range <>, natural range <>) of character;
attribute pin_number : string;
attribute array_pin_number : exemplar_string_array;
attribute pin_number of fpga_clk : signal is "Y2";
attribute pin_number of kb_clk : signal is "G6";
attribute pin_number of kb_data : signal is "H5";
attribute array_pin_number of db : signal is ("G17","J17","H19","J19","E18","F18","F21","E19","F19","G19");
attribute array_pin_number of hex0 : signal is ("H22","J22","L25","L26","E17","F22","G18");
attribute array_pin_number of hex1 : signal is ("U24","U23","W25","W22","W21","Y22","M24");
attribute array_pin_number of hex2 : signal is ("W28 ","W27 ","Y26 ","W26 ","Y25 ","AA26","AA25");
attribute array_pin_number of hex6 : signal is ("AC17","AA15","AB15","AB17","AA16","AB16","AA17");
attribute array_pin_number of hex7 : signal is ("AA14","AG18","AF17","AH17","AG17","AE17","AD17");

END CONTROL_Subsystem ;

--
-- VHDL Architecture The_Reverb_Revolutionary_lib.CONTROL_Subsystem.struct
--
-- Created:
--          by - emipi270.student-liu.se (muxen2-106.ad.liu.se)
--          at - 15:46:17 10/22/24
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY The_Reverb_Revolutionary_lib;

ARCHITECTURE struct OF CONTROL_Subsystem IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL down  : std_logic;
   SIGNAL left  : std_logic;
   SIGNAL right : std_logic;
   SIGNAL up    : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL Balance_setting_internal     : std_logic_vector (3 DOWNTO 0);
   SIGNAL Echo_room_setting_internal   : std_logic_vector (3 DOWNTO 0);
   SIGNAL Echo_volume_setting_internal : std_logic_vector (3 DOWNTO 0);
   SIGNAL Selected_setting_internal    : std_logic_vector (1 DOWNTO 0);
   SIGNAL Volume_setting_internal      : std_logic_vector (3 DOWNTO 0);


   -- Component Declarations
   COMPONENT Control_Hardware_testing
   PORT (
      Balance_setting     : IN     std_logic_vector (3 DOWNTO 0);
      Echo_room_setting   : IN     std_logic_vector (3 DOWNTO 0);
      Echo_volume_setting : IN     std_logic_vector (3 DOWNTO 0);
      Selected_setting    : IN     std_logic_vector (1 DOWNTO 0);
      Volume_setting      : IN     std_logic_vector (3 DOWNTO 0);
      fpga_clk            : IN     std_logic ;
      fpga_reset_n        : IN     std_logic ;
      Hex0                : OUT    std_logic_vector (6 DOWNTO 0);
      Hex1                : OUT    std_logic_vector (6 DOWNTO 0);
      Hex2                : OUT    std_logic_vector (6 DOWNTO 0);
      Hex6                : OUT    std_logic_vector (6 DOWNTO 0);
      Hex7                : OUT    std_logic_vector (6 DOWNTO 0);
      db                  : OUT    std_logic_vector (9 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT Control_Keyboard_Reader
   PORT (
      kb_clk       : IN     std_logic ;
      kb_data      : IN     std_logic ;
      left         : OUT    std_logic ;
      right        : OUT    std_logic ;
      up           : OUT    std_logic ;
      down         : OUT    std_logic ;
      fpga_clk     : IN     std_logic ;
      fpga_reset_n : IN     std_logic 
   );
   END COMPONENT;
   COMPONENT Control_Output_Setting
   PORT (
      down                : IN     std_logic ;
      left                : IN     std_logic ;
      right               : IN     std_logic ;
      up                  : IN     std_logic ;
      Balance_setting     : OUT    std_logic_vector (3 DOWNTO 0);
      Echo_room_setting   : OUT    std_logic_vector (3 DOWNTO 0);
      Echo_volume_setting : OUT    std_logic_vector (3 DOWNTO 0);
      Volume_setting      : OUT    std_logic_vector (3 DOWNTO 0);
      Selected_setting    : OUT    std_logic_vector (1 DOWNTO 0);
      fpga_clk            : IN     std_logic ;
      fpga_reset_n        : IN     std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Control_Hardware_testing USE ENTITY The_Reverb_Revolutionary_lib.Control_Hardware_testing;
   FOR ALL : Control_Keyboard_Reader USE ENTITY The_Reverb_Revolutionary_lib.Control_Keyboard_Reader;
   FOR ALL : Control_Output_Setting USE ENTITY The_Reverb_Revolutionary_lib.Control_Output_Setting;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_2 : Control_Hardware_testing
      PORT MAP (
         Balance_setting     => Balance_setting_internal,
         Echo_room_setting   => Echo_room_setting_internal,
         Echo_volume_setting => Echo_volume_setting_internal,
         Selected_setting    => Selected_setting_internal,
         Volume_setting      => Volume_setting_internal,
         fpga_clk            => fpga_clk,
         fpga_reset_n        => fpga_reset_n,
         Hex0                => Hex0,
         Hex1                => Hex1,
         Hex2                => Hex2,
         Hex6                => Hex6,
         Hex7                => Hex7,
         db                  => db
      );
   U_0 : Control_Keyboard_Reader
      PORT MAP (
         kb_clk       => kb_clk,
         kb_data      => kb_data,
         left         => left,
         right        => right,
         up           => up,
         down         => down,
         fpga_clk     => fpga_clk,
         fpga_reset_n => fpga_reset_n
      );
   U_1 : Control_Output_Setting
      PORT MAP (
         down                => down,
         left                => left,
         right               => right,
         up                  => up,
         Balance_setting     => Balance_setting_internal,
         Echo_room_setting   => Echo_room_setting_internal,
         Echo_volume_setting => Echo_volume_setting_internal,
         Volume_setting      => Volume_setting_internal,
         Selected_setting    => Selected_setting_internal,
         fpga_clk            => fpga_clk,
         fpga_reset_n        => fpga_reset_n
      );

   -- Implicit buffered output assignments
   Balance_setting     <= Balance_setting_internal;
   Echo_room_setting   <= Echo_room_setting_internal;
   Echo_volume_setting <= Echo_volume_setting_internal;
   Selected_setting    <= Selected_setting_internal;
   Volume_setting      <= Volume_setting_internal;

END struct;
