-- VHDL Entity The_Reverb_Revolutionary_lib.Visual_memory_get_address_boundries.generatedInstance
--
-- Created:
--          by - emipi270.student-liu.se (muxen2-104.ad.liu.se)
--          at - 16:52:37 10/08/24
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY Visual_memory_get_address_boundries IS
END Visual_memory_get_address_boundries ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF Visual_memory_get_address_boundries IS 
BEGIN


END generatedInstance;
