-- VHDL Entity The_Reverb_Revolutionary_lib.Visual_graphic_gen.symbol
--
-- Created:
--          by - emipi270.student-liu.se (muxen2-111.ad.liu.se)
--          at - 14:38:21 10/09/24
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY Visual_graphic_gen IS
   PORT( 
      SRAM_Data    : IN     std_logic_vector (15 DOWNTO 0);
      fpga_clk_65M : IN     std_logic;
      fpga_reset_n : IN     std_logic;
      hblanc       : OUT    std_logic;
      hcnt         : OUT    unsigned (10 DOWNTO 0);
      hsyncr       : OUT    std_logic;
      vblanc       : OUT    std_logic;
      vcnt         : OUT    unsigned (9 DOWNTO 0);
      vga_b        : OUT    std_logic_vector (7 DOWNTO 0);
      vga_blank_n  : OUT    std_logic;
      vga_g        : OUT    std_logic_vector (7 DOWNTO 0);
      vga_r        : OUT    std_logic_vector (7 DOWNTO 0);
      vga_sync     : OUT    std_logic;
      vsyncr       : OUT    std_logic
   );

-- Declarations

END Visual_graphic_gen ;

--
-- VHDL Architecture The_Reverb_Revolutionary_lib.Visual_graphic_gen.struct
--
-- Created:
--          by - emipi270.student-liu.se (muxen2-111.ad.liu.se)
--          at - 14:38:21 10/09/24
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY The_Reverb_Revolutionary_lib;

ARCHITECTURE struct OF Visual_graphic_gen IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL pixel_data : std_logic_vector(15 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL hblanc_internal      : std_logic;
   SIGNAL hcnt_internal        : unsigned (10 DOWNTO 0);
   SIGNAL hsyncr_internal      : std_logic;
   SIGNAL vblanc_internal      : std_logic;
   SIGNAL vcnt_internal        : unsigned (9 DOWNTO 0);
   SIGNAL vga_blank_n_internal : std_logic;


   -- Component Declarations
   COMPONENT Visual_hcnt_ent
   PORT (
      hcnt         : OUT    unsigned (10 DOWNTO 0);
      fpga_clk_65M : IN     std_logic ;
      fpga_reset_n : IN     std_logic 
   );
   END COMPONENT;
   COMPONENT Visual_hsyncr_ent
   PORT (
      hsyncr       : OUT    std_logic ;
      hblanc       : OUT    std_logic ;
      hcnt         : IN     unsigned (10 DOWNTO 0);
      fpga_clk_65M : IN     std_logic ;
      fpga_reset_n : IN     std_logic 
   );
   END COMPONENT;
   COMPONENT Visual_or_ent
   PORT (
      hblanc       : IN     std_logic ;
      vblanc       : IN     std_logic ;
      fpga_clk_65M : IN     std_logic ;
      vga_blank_n  : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT Visual_pixel_reg
   PORT (
      SRAM_Data    : IN     std_logic_vector (15 DOWNTO 0);
      fpga_clk_65M : IN     std_logic ;
      fpga_reset_n : IN     std_logic ;
      pixel_data   : OUT    std_logic_vector (15 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT Visual_vcnt_ent
   PORT (
      vcnt         : OUT    unsigned (9 DOWNTO 0);
      hsyncr       : IN     std_logic ;
      fpga_clk_65M : IN     std_logic ;
      fpga_reset_n : IN     std_logic 
   );
   END COMPONENT;
   COMPONENT Visual_vga_gen
   PORT (
      pixel_data   : IN     std_logic_vector (15 DOWNTO 0);
      vga_r        : OUT    std_logic_vector (7 DOWNTO 0);
      vga_g        : OUT    std_logic_vector (7 DOWNTO 0);
      vga_b        : OUT    std_logic_vector (7 DOWNTO 0);
      fpga_clk_65M : IN     std_logic ;
      vga_blank_n  : IN     std_logic 
   );
   END COMPONENT;
   COMPONENT Visual_vsyncr_ent
   PORT (
      vcnt         : IN     unsigned (9 DOWNTO 0);
      vga_sync     : OUT    std_logic ;
      vsyncr       : OUT    std_logic ;
      vblanc       : OUT    std_logic ;
      fpga_clk_65M : IN     std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Visual_hcnt_ent USE ENTITY The_Reverb_Revolutionary_lib.Visual_hcnt_ent;
   FOR ALL : Visual_hsyncr_ent USE ENTITY The_Reverb_Revolutionary_lib.Visual_hsyncr_ent;
   FOR ALL : Visual_or_ent USE ENTITY The_Reverb_Revolutionary_lib.Visual_or_ent;
   FOR ALL : Visual_pixel_reg USE ENTITY The_Reverb_Revolutionary_lib.Visual_pixel_reg;
   FOR ALL : Visual_vcnt_ent USE ENTITY The_Reverb_Revolutionary_lib.Visual_vcnt_ent;
   FOR ALL : Visual_vga_gen USE ENTITY The_Reverb_Revolutionary_lib.Visual_vga_gen;
   FOR ALL : Visual_vsyncr_ent USE ENTITY The_Reverb_Revolutionary_lib.Visual_vsyncr_ent;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : Visual_hcnt_ent
      PORT MAP (
         hcnt         => hcnt_internal,
         fpga_clk_65M => fpga_clk_65M,
         fpga_reset_n => fpga_reset_n
      );
   U_2 : Visual_hsyncr_ent
      PORT MAP (
         hsyncr       => hsyncr_internal,
         hblanc       => hblanc_internal,
         hcnt         => hcnt_internal,
         fpga_clk_65M => fpga_clk_65M,
         fpga_reset_n => fpga_reset_n
      );
   U_4 : Visual_or_ent
      PORT MAP (
         hblanc       => hblanc_internal,
         vblanc       => vblanc_internal,
         fpga_clk_65M => fpga_clk_65M,
         vga_blank_n  => vga_blank_n_internal
      );
   U_5 : Visual_pixel_reg
      PORT MAP (
         SRAM_Data    => SRAM_Data,
         fpga_clk_65M => fpga_clk_65M,
         fpga_reset_n => fpga_reset_n,
         pixel_data   => pixel_data
      );
   U_1 : Visual_vcnt_ent
      PORT MAP (
         vcnt         => vcnt_internal,
         hsyncr       => hsyncr_internal,
         fpga_clk_65M => fpga_clk_65M,
         fpga_reset_n => fpga_reset_n
      );
   U_6 : Visual_vga_gen
      PORT MAP (
         pixel_data   => pixel_data,
         vga_r        => vga_r,
         vga_g        => vga_g,
         vga_b        => vga_b,
         fpga_clk_65M => fpga_clk_65M,
         vga_blank_n  => vga_blank_n_internal
      );
   U_3 : Visual_vsyncr_ent
      PORT MAP (
         vcnt         => vcnt_internal,
         vga_sync     => vga_sync,
         vsyncr       => vsyncr,
         vblanc       => vblanc_internal,
         fpga_clk_65M => fpga_clk_65M
      );

   -- Implicit buffered output assignments
   hblanc      <= hblanc_internal;
   hcnt        <= hcnt_internal;
   hsyncr      <= hsyncr_internal;
   vblanc      <= vblanc_internal;
   vcnt        <= vcnt_internal;
   vga_blank_n <= vga_blank_n_internal;

END struct;
