-- VHDL Entity The_Reverb_Revolutionary_lib.Visual_memory_interface.interface
--
-- Created:
--          by - matho019.student-liu.se (muxen2-106.ad.liu.se)
--          at - 16:27:43 11/11/24
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY Visual_memory_interface IS
   PORT( 
      Audio_bar             : IN     std_logic_vector (17 DOWNTO 0);
      Balance_setting       : IN     std_logic_vector (3 DOWNTO 0);
      Echo_room_setting     : IN     std_logic_vector (3 DOWNTO 0);
      Echo_volume_setting   : IN     std_logic_vector (3 DOWNTO 0);
      Selected_setting      : IN     std_logic_vector (1 DOWNTO 0);
      Volume_setting        : IN     std_logic_vector (3 DOWNTO 0);
      c0                    : IN     STD_LOGIC;
      hblanc                : IN     std_logic;
      hcnt                  : IN     unsigned (10 DOWNTO 0);
      locked                : IN     STD_LOGIC;
      vblanc                : IN     std_logic;
      vcnt                  : IN     unsigned (9 DOWNTO 0);
      vga_hsync_n           : IN     std_logic;
      vga_vsync_n           : IN     std_logic;
      Screen_overlay        : OUT    std_logic_vector (15 DOWNTO 0);
      Screen_overlay_active : OUT    std_logic;
      sram_address          : OUT    std_logic_vector (19 DOWNTO 0);
      sram_ce_n             : OUT    std_logic;
      sram_lb_n             : OUT    std_logic;
      sram_oe_n             : OUT    std_logic;
      sram_ub_n             : OUT    std_logic;
      sram_we_n             : OUT    std_logic
   );

-- Declarations

END Visual_memory_interface ;

--
-- VHDL Architecture The_Reverb_Revolutionary_lib.Visual_memory_interface.struct
--
-- Created:
--          by - matho019.student-liu.se (muxen2-106.ad.liu.se)
--          at - 16:27:43 11/11/24
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY The_Reverb_Revolutionary_lib;

ARCHITECTURE struct OF Visual_memory_interface IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT Visual_memory_read
   PORT (
      c0                    : IN     STD_LOGIC ;
      hblanc                : IN     std_logic ;
      hcnt                  : IN     unsigned (10 DOWNTO 0);
      locked                : IN     STD_LOGIC ;
      vblanc                : IN     std_logic ;
      vcnt                  : IN     unsigned (9 DOWNTO 0);
      vga_hsync_n           : IN     std_logic ;
      vga_vsync_n           : IN     std_logic ;
      sram_lb_n             : OUT    std_logic ;
      sram_oe_n             : OUT    std_logic ;
      sram_ub_n             : OUT    std_logic ;
      sram_ce_n             : OUT    std_logic ;
      sram_we_n             : OUT    std_logic ;
      Screen_overlay        : OUT    std_logic_vector (15 DOWNTO 0);
      Screen_overlay_active : OUT    std_logic ;
      sram_address          : OUT    std_logic_vector (19 DOWNTO 0);
      Balance_setting       : IN     std_logic_vector (3 DOWNTO 0);
      Echo_room_setting     : IN     std_logic_vector (3 DOWNTO 0);
      Echo_volume_setting   : IN     std_logic_vector (3 DOWNTO 0);
      Volume_setting        : IN     std_logic_vector (3 DOWNTO 0);
      Selected_setting      : IN     std_logic_vector (1 DOWNTO 0);
      Audio_bar             : IN     std_logic_vector (17 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Visual_memory_read USE ENTITY The_Reverb_Revolutionary_lib.Visual_memory_read;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : Visual_memory_read
      PORT MAP (
         c0                    => c0,
         hblanc                => hblanc,
         hcnt                  => hcnt,
         locked                => locked,
         vblanc                => vblanc,
         vcnt                  => vcnt,
         vga_hsync_n           => vga_hsync_n,
         vga_vsync_n           => vga_vsync_n,
         sram_lb_n             => sram_lb_n,
         sram_oe_n             => sram_oe_n,
         sram_ub_n             => sram_ub_n,
         sram_ce_n             => sram_ce_n,
         sram_we_n             => sram_we_n,
         Screen_overlay        => Screen_overlay,
         Screen_overlay_active => Screen_overlay_active,
         sram_address          => sram_address,
         Balance_setting       => Balance_setting,
         Echo_room_setting     => Echo_room_setting,
         Echo_volume_setting   => Echo_volume_setting,
         Volume_setting        => Volume_setting,
         Selected_setting      => Selected_setting,
         Audio_bar             => Audio_bar
      );

END struct;
